packages:
  - 'client/apps/*'
  - 'client/libs/*'
  - 'server/apps/*'
  - 'server/libs/*'
  - 'common/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
