import { Injectable } from '@nestjs/common'
import { Country, LocationRepository } from '@domains/location/location.repository'

@Injectable()
export class StaticLocationRepository implements LocationRepository {
  private readonly countries: Country[] = [
    { id: 'nigeria', name: 'Nigeria' },
    { id: 'kenya', name: 'Kenya' },
  ]

  private readonly CITIES_DATA: Record<string, string[]> = {
    nigeria: [
      'Aba',
      'Abakaliki',
      'Abeokuta',
      'Abuja',
      'Ado Ekiti',
      'Akure',
      'Asaba',
      'Awka',
      'Badagry',
      'Bama',
      'Bauchi',
      'Benin City',
      'Bida',
      'Buguma',
      'Calabar',
      'Enugu',
      'Epe',
      'Funtua',
      'Garki',
      'Gashua',
      'Gboko',
      'Gbongan',
      'Gombe',
      'Gusau',
      'Ibadan',
      'Ife',
      'Igboho',
      'Ijebu Ode',
      'Ijero',
      'Ikare',
      'Ikeja',
      'Ikorodu',
      'Ikot Ekpene',
      'Ila',
      'Ilawe Ekiti',
      'Ilesa',
      'Ilorin',
      'Ise Ekiti',
      'Iseyin',
      'Iwo',
      'Jalingo',
      'Jos',
      'Kaduna',
      'Kano',
      'Katsina',
      'Kisi',
      'Kukawa',
      'Lafia',
      'Lagos',
      'Lavun',
      'Maiduguri',
      'Makurdi',
      'Minna',
      'Mokwa',
      'Mubi',
      'Nsukka',
      'Obafemi Owode',
      'Ogbomosho',
      'Okene',
      'Okigwe',
      'Okpoko',
      'Ondo',
      'Onitsha',
      'Osogbo',
      'Otukpo',
      'Owerri',
      'Owo',
      'Oyo',
      'Port Harcourt',
      'Potiskum',
      'Sagamu',
      'Sapele',
      'Shaki',
      'Sokoto',
      'Suleja',
      'Ugep',
      'Umuahia',
      'Uromi',
      'Uyo',
      'Warri',
      'Yola',
      'Zaria',
    ],
    kenya: [
      'Baragoi',
      'Bondo',
      'Bungoma',
      'Busia',
      'Butere',
      'Dadaab',
      'Diani Beach',
      'Eldoret',
      'Emali',
      'Embu',
      'Garissa',
      'Gede',
      'Gem',
      'Hola',
      'Homa Bay',
      'Isiolo',
      'Kitui',
      'Kibwezi',
      'Kajiado',
      'Kakamega',
      'Kakuma',
      'Kapenguria',
      'Kericho',
      'Keroka',
      'Kiambu',
      'Kilifi',
      'Kisii',
      'Kisumu',
      'Kitale',
      'Lamu',
      'Langata',
      'Litein',
      'Lodwar',
      'Lokichoggio',
      'Londiani',
      'Loyangalani',
      'Machakos',
      'Makindu',
      'Malindi',
      'Mandera',
      'Maralal',
      'Marsabit',
      'Meru',
      'Mombasa',
      'Moyale',
      'Mtwapa',
      'Mumias',
      'Muranga',
      'Mutomo',
      'Nairobi',
      'Naivasha',
      'Nakuru',
      'Namanga',
      'Nanyuki',
      'Naro Moru',
      'Narok',
      'Nyahururu',
      'Nyeri',
      'Ruiru',
      'Siaya',
      'Shimoni',
      'Takaungu',
      'Thika',
      'Ugunja',
      'Vihiga',
      'Voi',
      'Wajir',
      'Watamu',
      'Webuye',
      'Wote',
      'Wundanyi',
    ],
  }

  async getCountries(): Promise<Country[]> {
    return this.countries
  }

  async getCities(countryId: string): Promise<string[]> {
    const key = countryId.toLowerCase()
    return this.CITIES_DATA[key] || []
  }
}
