'use client'

import React from 'react'
import { useRouter } from 'next/navigation'
import { PayPageShell } from '@/features/dashboard/components/payment/PayPageShell'

export default function TermsOfUsePage() {
  const router = useRouter()

  return (
    <PayPageShell
      title="Terms of Use"
      showBack
      onBack={() => router.push('/dashboard/legal')}
    >
      <div className="legal-document">
        <header className="legal-document__header">
          <p className="legal-document__update-date">Last updated: August 24, 2026</p>
        </header>

        <section className="legal-document__content">
          <p style={{ marginBottom: '24px', textTransform: 'uppercase', fontWeight: 600, letterSpacing: '0.05em' }}>
            UPWARD BY LIVEABLE SMARTCITY TECHNOLOGIES — TERMS OF USE
          </p>

          <p style={{ marginBottom: '24px' }}>
            These Terms of Use (“Terms”) constitute a legally binding agreement between any person or entity accessing or using the Upward Platform (“User,” “Customer,” “you,” or “your”) and Liveable Smartcity Technologies Limited (“Liveable,” “we,” “us,” or “our”), which owns, operates, and manages the Platform. Please read these Terms of Service carefully as they affect Your rights and liabilities under the Applicable Laws. By accessing, subscribing to, or using the Platform, you acknowledge that you have read, understood, and agreed to be bound by these Terms.
          </p>

          <h2>1. DEFINITIONS AND INTERPRETATION</h2>
          <ul>
            <li>
              <strong>1.1. &ldquo;Account&rdquo;</strong> means the registered user account created to access the Platform.
            </li>
            <li>
              <strong>1.2. &ldquo;Applicable Law&rdquo;</strong> means all laws, regulations, directives, and regulatory requirements applicable in the Federal Republic of Nigeria.
            </li>
            <li>
              <strong>1.3. &ldquo;Confidential Information&rdquo;</strong> means non-public information disclosed by either party, whether oral, written, electronic, or otherwise, including business, technical, financial, and operational information.
            </li>
            <li>
              <strong>1.4. &ldquo;Platform&rdquo;</strong> means the Upward SaaS solution, including all web applications, mobile applications, APIs, software, databases, dashboards, infrastructure, documentation, and related systems.
            </li>
            <li>
              <strong>1.5. &ldquo;Services&rdquo;</strong> means the subscription-based property management, listing, CRM, analytics, automation, and related services made available via the Platform.
            </li>
            <li>
              <strong>1.6. &ldquo;Subscription Term&rdquo;</strong> means the period during which a User is authorized to access and use the Platform.
            </li>
            <li>
              <strong>1.7. &ldquo;User Data&rdquo;</strong> means all data, content, listings, information, images, documents, and materials uploaded or generated by the User on the Platform.
            </li>
          </ul>

          <h2>2. INTRODUCTION</h2>
          <p>
            Upward is a platform that turns your rent payments into a verified rental history. It is an advanced property management and financial technology infrastructure that enables landlords, property managers, institutional investors, and tenants to optimize rental operations, access rent management tools, build tenant financial profiles, and facilitate property growth solutions. Upward provides the Services strictly as a technology service provider and on a service provider basis. All tenancy agreements, financial transactions, credit reporting preferences, property listings, and related contractual arrangements are entered into directly between Users and their tenants, financial institutions, or counterparties.
          </p>
          <p>Accordingly, Upward does not:</p>
          <ul>
            <li><strong>2.1.</strong> Act as a bank, licensed financial institution, credit bureau, real estate broker, or leasing agent;</li>
            <li><strong>2.2.</strong> Guarantee rental yields, tenant credit approvals, financial performance, or counterparty reliability;</li>
            <li><strong>2.3.</strong> Endorse or validate property valuations, tenant creditworthiness, or listings uploaded by Users;</li>
            <li><strong>2.4.</strong> Assume liability for rental defaults, loan non-payment, lease disputes, financial losses, or property damage.</li>
          </ul>
          <p>
            You acknowledge that Upward merely provides digital infrastructure to facilitate property management, financial integration, and tenant mobility processes.
          </p>

          <h2>3. ELIGIBILITY AND REGISTRATION</h2>
          <p><strong>3.1.</strong> You represent and warrant that:</p>
          <ul>
            <li>
              <strong>3.1.1.</strong> Where applicable, you are duly incorporated and validly existing under Nigerian laws as a company, business name or any other business structure recognized under the Companies and Allied Matters 2020;
            </li>
            <li>
              <strong>3.1.2.</strong> You possess full authority to enter into and bind your organization to these Terms;
            </li>
            <li>
              <strong>3.1.3.</strong> Your use of the Platform shall comply with Applicable Laws.
            </li>
          </ul>
          <p>
            <strong>3.2.</strong> We reserve the right to suspend access where eligibility requirements are not satisfied.
          </p>

          <h2>4. FREE TRIAL</h2>
          <p>
            <strong>4.1.</strong> We may, at our discretion, provide a fourteen (14) day free trial (&ldquo;Free Trial&rdquo;).
          </p>
          <p><strong>4.2.</strong> During the Free Trial:</p>
          <ul>
            <li><strong>4.2.1.</strong> The Platform is provided strictly for evaluation purposes;</li>
            <li><strong>4.2.2.</strong> Services are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis;</li>
            <li><strong>4.2.3.</strong> We make no guarantees regarding availability, continuity, or performance.</li>
          </ul>
          <p>
            <strong>4.3.</strong> We may modify, restrict, or discontinue the Free Trial at any time without liability.
          </p>

          <h2>5. SCOPE OF SERVICES</h2>
          <p><strong>5.1.</strong> The Platform enables Users to:</p>
          <ul>
            <li><strong>5.1.1.</strong> List and market real estate properties;</li>
            <li><strong>5.1.2.</strong> Screen prospective tenants and build comprehensive tenant financial profiles;</li>
            <li><strong>5.1.3.</strong> Track payments and operational performance;</li>
            <li><strong>5.1.4.</strong> Access analytics and reporting tools;</li>
            <li><strong>5.1.5.</strong> Access tenant mobility tools, rent financing, and property growth solutions;</li>
            <li><strong>5.1.6.</strong> Integrate with approved third-party systems.</li>
          </ul>
          <p>
            <strong>5.2.</strong> We may update, enhance, suspend, or modify features from time to time, provided that the core functionality of the Platform is not materially diminished.
          </p>
          <p>
            <strong>5.3.</strong> Custom development, bespoke integrations, or enterprise configurations shall be subject to separate written agreements and additional fees.
          </p>

          <h2>6. SUBSCRIPTION AND PAYMENT</h2>
          <p><strong>6.1.</strong> Access to the Platform is subject to payment of applicable Subscription Fees.</p>
          <p><strong>6.2.</strong> Subscription Fees are payable annually in advance and are calculated based on the number of property units, tenants, or agreed plan tier.</p>
          <p><strong>6.3.</strong> Additional units added during the Subscription Term may attract prorated charges.</p>
          <p><strong>6.4.</strong> Subscription renewals shall occur automatically unless cancelled prior to renewal.</p>
          <p><strong>6.5.</strong> We may revise fees upon prior written notice before renewal. Continued use after notice constitutes acceptance of the revised pricing.</p>
          <p><strong>6.6.</strong> All fees are exclusive of applicable taxes, which remain your responsibility.</p>

          <h2>7. THIRD PARTY SERVICES</h2>
          <p>The Platform may integrate Third-Party Providers. Upward does not control third-party systems and:</p>
          <ul>
            <li><strong>7.1.</strong> Is not responsible for acts, omissions, errors, or failures of such providers;</li>
            <li><strong>7.2.</strong> Does not guarantee uninterrupted third-party services.</li>
          </ul>
          <p>
            Your use of third-party services is subject to their independent terms and policies.
          </p>

          <h2>8. USER RESPONSIBILITIES</h2>
          <p><strong>8.1.</strong> You agree to:</p>
          <ul>
            <li><strong>8.1.1.</strong> Provide accurate, complete, and updated information;</li>
            <li><strong>8.1.2.</strong> Maintain confidentiality of login credentials;</li>
            <li><strong>8.1.3.</strong> Immediately notify us of unauthorized access;</li>
            <li><strong>8.1.4.</strong> Ensure that all listings and uploaded content are lawful and accurate.</li>
          </ul>
          <p><strong>8.2.</strong> You shall not:</p>
          <ul>
            <li><strong>8.2.1.</strong> Reverse engineer, decompile, copy, or replicate any part of the Platform;</li>
            <li><strong>8.2.2.</strong> Introduce malware or malicious code;</li>
            <li><strong>8.2.3.</strong> Circumvent security or authentication systems;</li>
            <li><strong>8.2.4.</strong> Upload fraudulent, misleading, defamatory, or unlawful content.</li>
          </ul>
          <p>
            <strong>8.3.</strong> You remain solely responsible for all User Data and property listings uploaded to the Platform.
          </p>

          <h2>9. ONBOARDING AND IMPLEMENTATION</h2>
          <p><strong>9.1.</strong> You are responsible for uploading your data and configuring your operations within the Platform.</p>
          <p><strong>9.2.</strong> We may provide:</p>
          <ul>
            <li><strong>9.2.1.</strong> Remote onboarding assistance;</li>
            <li><strong>9.2.2.</strong> Documentation and user guides;</li>
            <li><strong>9.2.3.</strong> Paid onsite onboarding services (subject to agreed fees).</li>
          </ul>
          <p>
            <strong>9.3.</strong> We are not responsible for errors arising from inaccurate or incomplete data provided by you.
          </p>

          <h2>10. SUBSCRIPTION FEES</h2>
          <p>
            <strong>10.1. Subscription Fees:</strong> Access to and use of the Upward Tenant App is currently provided to Tenants free of subscription charge/fees. Upward reserves the right to introduce optional value-added services or financial products which may carry separate transaction fees, disclosed prior to use.
          </p>
          <p>
            <strong>10.2. Landlords and Property Management Subscription:</strong> Subscription Fees displayed on the Platform or Website apply exclusively to Landlords, Property Managers, and Property Management Businesses.
          </p>
          <p>
            <strong>10.3. Additional Units:</strong> Additional units added during the Subscription Term shall attract pro-rated charges.
          </p>
          <p>
            <strong>10.4. Renewal:</strong> Subscriptions automatically renew annually unless terminated in accordance with these Terms.
          </p>
          <p>
            <strong>10.5. Fee Adjustments:</strong> We may revise Subscription Fees upon providing at least thirty (30) days’ written notice prior to renewal. Continued use after such notice constitutes acceptance.
          </p>
          <p>
            <strong>10.6. Taxes:</strong> All fees are exclusive of VAT or other applicable taxes, which shall be borne by the User.
          </p>

          <h2>11. SERVICE LEVEL AND AVAILABILITY</h2>
          <p>
            <strong>11.1.</strong> We aim to maintain at least ninety-five percent (95%) uptime annually, excluding:
          </p>
          <ul>
            <li><strong>11.1.1.</strong> Scheduled maintenance (with prior notice);</li>
            <li><strong>11.1.2.</strong> Emergency maintenance;</li>
            <li><strong>11.1.3.</strong> Downtime caused by third-party service providers.</li>
          </ul>
          <p>
            <strong>11.2.</strong> We do not guarantee uninterrupted or error-free operation.
          </p>

          <h2>12. DATA UTILIZATION</h2>
          <p>
            <strong>12.1. Consent to Data Utilization:</strong> By registering an account, signing up, or utilizing the Platform, you expressly authorize and grant Upward a non-exclusive, worldwide, royalty-free, perpetual license to collect, process, analyze, aggregate, and utilize your personal data, rental history, account information, and payment data for platform operations, risk assessment, credit profile modeling and automated decision-making processes.
          </p>
          <p>
            <strong>12.2. Automated Decision-Making &amp; Analytics:</strong> You acknowledge and agree that Upward utilizes automated systems and predictive analytics to generate scores, reports, automated tenant screening outcomes, and operational decisions. Upward makes no guarantees regarding the performance or outcomes generated by these automated processes.
          </p>
          <p>
            <strong>12.3. Waiver of Future Benefits:</strong> You explicitly acknowledge and agree that Upward’s collection, processing, and application of your data or payment data for decision-making, platform enhancement, or automated profiling does not entitle you to any financial equity, platform royalties, compensation, profit-sharing, IP rights, or future commercial benefits derived from such data utilization or system outputs.
          </p>

          <h2>13. DATA OWNERSHIP AND PROTECTION</h2>
          <p><strong>13.1.</strong> You retain all rights to your User Data.</p>
          <p>
            <strong>13.2.</strong> Upon termination, you may request export of your User Data in a commonly used, machine-readable format within thirty (30) days.
          </p>
          <p>
            <strong>13.3.</strong> We shall implement reasonable administrative, technical, and organizational measures to safeguard User Data in accordance with Applicable Law.
          </p>
          <p>
            <strong>13.4.</strong> You retain the right to request information regarding the logic involved in automated decisions affecting you, as well as the right to request human review where an automated decision produces significant legal or contractual effects.
          </p>

          <h2>14. INTELLECTUAL PROPERTY</h2>
          <p>
            <strong>14.1.</strong> All intellectual property rights in the Platform remain exclusively owned by the Company.
          </p>
          <p>
            <strong>14.2.</strong> We grant you a limited, non-exclusive, non-transferable, revocable license to use the Platform solely for internal business purposes during the Subscription Term.
          </p>
          <p>
            <strong>14.3.</strong> Any feedback, suggestions, or improvements provided by you may be used by us without restriction or compensation.
          </p>

          <h2>15. DISCLAIMER</h2>
          <p>
            The Platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We do not guarantee uninterrupted service or tenant performance.
          </p>

          <h2>16. CONFIDENTIALITY</h2>
          <p><strong>16.1.</strong> Each party shall:</p>
          <ul>
            <li><strong>16.1.1.</strong> Maintain strict confidentiality of Confidential Information;</li>
            <li><strong>16.1.2.</strong> Use such information solely for purposes of these Terms;</li>
            <li><strong>16.1.3.</strong> Not disclose such information without prior written consent.</li>
          </ul>
          <p>
            <strong>16.2.</strong> Confidentiality obligations survive termination for a period of five (5) years.
          </p>

          <h2>17. REPRESENTATIONS AND WARRANTIES</h2>
          <p><strong>17.1.</strong> Each party represents that:</p>
          <ul>
            <li><strong>17.1.1.</strong> It has full legal capacity to enter into these Terms;</li>
            <li><strong>17.1.2.</strong> These Terms constitute binding and enforceable obligations.</li>
          </ul>
          <p>
            Except as expressly stated, the Platform is provided without warranties of merchantability, fitness for a particular purpose, or non-infringement.
          </p>

          <h2>18. INDEMNITY</h2>
          <p>
            <strong>18.1.</strong> Each party shall indemnify and hold harmless the other against third-party claims arising from:
          </p>
          <ul>
            <li><strong>18.1.1.</strong> Breach of these Terms;</li>
            <li><strong>18.1.2.</strong> Gross negligence or wilful misconduct;</li>
            <li><strong>18.1.3.</strong> Intellectual property infringement;</li>
            <li><strong>18.1.4.</strong> Fraudulent acts.</li>
          </ul>

          <h2>19. LIMITATION OF LIABILITY</h2>
          <p><strong>19.1.</strong> To the fullest extent permitted by law:</p>
          <ul>
            <li><strong>19.1.1.</strong> Neither party shall be liable for indirect, incidental, consequential, or special damages;</li>
            <li><strong>19.1.2.</strong> We shall not be liable for loss of profits, revenue, goodwill, data, or business opportunity;</li>
            <li><strong>19.1.3.</strong> Our aggregate liability shall not exceed the total Subscription Fees paid in the twelve (12) months preceding the claim.</li>
          </ul>

          <h2>20. TERMINATION</h2>
          <p><strong>20.1.</strong> We may suspend or terminate access where:</p>
          <ul>
            <li><strong>20.1.1.</strong> Fees remain unpaid;</li>
            <li><strong>20.1.2.</strong> You materially breach these Terms;</li>
            <li><strong>20.1.3.</strong> You engage in unlawful conduct.</li>
          </ul>
          <p>
            <strong>20.2.</strong> Either party may terminate upon thirty (30) days’ written notice.
          </p>
          <p>
            <strong>20.3.</strong> Immediate termination may occur in cases of insolvency or material breach.
          </p>

          <h2>21. EFFECT OF TERMINATION</h2>
          <p><strong>21.1.</strong> Upon termination:</p>
          <ul>
            <li><strong>21.1.1.</strong> Access to the Platform ceases immediately;</li>
            <li><strong>21.1.2.</strong> Outstanding fees become due;</li>
            <li><strong>21.1.3.</strong> Confidential Information must be returned or deleted;</li>
            <li><strong>21.1.4.</strong> Accrued rights survive termination.</li>
          </ul>

          <h2>22. FORCE MAJEURE</h2>
          <p>
            <strong>22.1.</strong> Neither party shall be liable for failure nor delay due to causes beyond reasonable control.
          </p>
          <p>
            <strong>22.2.</strong> If such an event continues for sixty (60) consecutive days, either party may terminate upon fifteen (15) days’ written notice.
          </p>

          <h2>23. ASSIGNMENT</h2>
          <p>
            Neither party may assign or transfer its rights without prior written consent, except to an Affiliate or in connection with a merger or acquisition.
          </p>

          <h2>24. ENTIRE AGREEMENT</h2>
          <p>
            These Terms constitute the entire agreement and supersede all prior discussions or understandings.
          </p>

          <h2>25. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
          <p>
            <strong>25.1.</strong> These Terms shall be governed by the laws of the Federal Republic of Nigeria.
          </p>
          <p>
            <strong>25.2.</strong> Any dispute shall first be resolved amicably.
          </p>
          <p>
            <strong>25.3.</strong> Failing amicable resolution, disputes shall be referred to arbitration in Lagos under the Arbitration and Mediation Act 2023.
          </p>

          <h2>26. CONTACT INFORMATION</h2>
          <p>
            For enquiries or notices, please contact us at: <a href="mailto:hello@goodtenants.africa">hello@goodtenants.africa</a>.
          </p>
        </section>
      </div>
    </PayPageShell>
  )
}
